version: '2.4'
services:
  web:
    build:
      context: ./maomaorou-class-web
      target: dev
  
      dockerfile: Dockerfile
    volumes:
        - ./maomaorou-class-web:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3100:3100"
    env_file:
      - ./maomaorou-class-web/.env.local
  

  
    
    networks:
      maomaorou_net:


      
networks:
  maomaorou_net: