version: '2.4'
services:
  web:
    build:
      context: ./maomaorou-class-web
      target: dev
      dockerfile: Dockerfile
    volumes:
        - ./maomaorou-class-web:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"
    env_file:
      - ./maomaorou-class-web/.env.local
    depends_on:
      - strapi
    networks:
      maomaorou_net:

  strapi:
    build:
      context: ./maomaorou-class-strapi
      target: dev
      dockerfile: Dockerfile
    volumes:
      - ./maomaorou-class-strapi:/app
      - /app/node_modules
      - /app/dist
      - /app/.strapi
    env_file:
      - ./maomaorou-class-strapi/.env
    environment:
      - DATABASE_HOST=database
    ports:
      - "1337:1337"
    depends_on:
      - database
    networks:
      maomaorou_net:
    command: bash -c "yarn develop --watch-admin"

  database:
    image: mysql:5.7
    platform: linux/amd64
    networks:
      maomaorou_net:
    ports:
      - 3306:3306
    env_file:
      - .env.db

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    env_file:
      - .env.db
    networks:
      maomaorou_net:
      
networks:
  maomaorou_net: