version: '2.4'
services:
  web:
    build:
      context: ./maomaorou-class-web
      target: production
      dockerfile: Dockerfile
    volumes:
        - ./maomaorou-class-web:/app
        - /app/node_modules
        - /app/.next
    env_file:
      - ./maomaorou-class-web/.env.local
    ports:
      - "3100:3100"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  
  
